[functions]
  directory = "$api/"

[[redirects]]
from = "/api/*"
to = "/.netlify/functions/:splat"
status = 200
force = true

[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization"
